// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2U0eCGiRi7hBmYhbND4EHjoB8ajpMpXQ',
    appId: '1:33215206710:web:9f690f6b4e56a596b50f97',
    messagingSenderId: '33215206710',
    projectId: 'laundry-b54c8',
    authDomain: 'laundry-b54c8.firebaseapp.com',
    storageBucket: 'laundry-b54c8.appspot.com',
    measurementId: 'G-JMJJZGCGX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKH7oliq46OkacSzSOSKfTmocA1QUDFK4',
    appId: '1:33215206710:android:72517a435953f15fb50f97',
    messagingSenderId: '33215206710',
    projectId: 'laundry-b54c8',
    storageBucket: 'laundry-b54c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlKZhl-l-E10FQHjkkDDHCdeYQvhGCks',
    appId: '1:33215206710:ios:ddd9bcb3d9eaa57ab50f97',
    messagingSenderId: '33215206710',
    projectId: 'laundry-b54c8',
    storageBucket: 'laundry-b54c8.appspot.com',
    iosBundleId: 'com.example.laundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFlKZhl-l-E10FQHjkkDDHCdeYQvhGCks',
    appId: '1:33215206710:ios:64b4d173f8a4220db50f97',
    messagingSenderId: '33215206710',
    projectId: 'laundry-b54c8',
    storageBucket: 'laundry-b54c8.appspot.com',
    iosBundleId: 'com.example.laundry.RunnerTests',
  );
}
